export const userDataExample = {
  data: {
    fullname: 'erick ake',
    id_usuario: 4,
    primer_nombre: 'erick',
    segundo_nombre: null,
    primer_apellido: 'ake',
    segundo_apellido: null,
    email_usuario: 'erikdemo@example.com',
    user_name: 'erik_ake',
    fecha_alta: '2022-08-26T12:36:25.430Z',
    fecha_modificado: null,
    id_role: 1,
    id_empresa: 1,
    business: {
      id: 1,
      nombre: 'MACROPAY',
      razon_social: 'CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V.',
      no_telefono_1: '7777777777',
      no_telefono_2: null,
      direccion: '23 No 53A ENTRE 8 Y 10',
      colonia: 'MEXICO',
      ciudad: 'Mérida',
      estado: 'Yucatán',
      codigo_postal: '97125',
      estatus: 1,
      oper_alta: 'sys',
      fecha_alta: '2021-12-12T23:32:29.960Z',
      oper_modificacion: '0000007128',
      fecha_modificacion: '2022-06-13T11:23:17.387Z',
      oper_baja: null,
      fecha_baja: null,
      nombre_socio: null,
      clabe_interbancaria: null,
      fg_es_fronterizo: 0,
    },
    profile: {
      id: 1,
      nombre: 'Super Administrador',
      key: 'superadmin',
      descripcion: null,
      estatus: 1,
      modules: [
        {
          id_modulo: 1,
          nombre_modulo: 'Dashboard',
          path: '/dashboard',
          descripcion: null,
          estatus: 1,
          permissions: [],
        },
        {
          id_modulo: 2,
          nombre_modulo: 'Configuracion',
          path: '/agent-settings',
          descripcion: null,
          estatus: 1,
          permissions: [],
        },
      ],
    },
  },
  token:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZ1bGxuYW1lIjoiZXJpY2sgYWtlIiwiaWRfdXN1YXJpbyI6NCwicHJpbWVyX25vbWJyZSI6ImVyaWNrIiwic2VndW5kb19ub21icmUiOm51bGwsInByaW1lcl9hcGVsbGlkbyI6ImFrZSIsInNlZ3VuZG9fYXBlbGxpZG8iOm51bGwsImVtYWlsX3VzdWFyaW8iOiJlcmlrZGVtb0BleGFtcGxlLmNvbSIsInVzZXJfbmFtZSI6ImVyaWtfYWtlIiwiZmVjaGFfYWx0YSI6IjIwMjItMDgtMjZUMTI6MzY6MjUuNDMwWiIsImZlY2hhX21vZGlmaWNhZG8iOm51bGwsImlkX3JvbGUiOjEsImlkX2VtcHJlc2EiOjEsImJ1c2luZXNzIjp7ImlkIjoxLCJub21icmUiOiJNQUNST1BBWSIsInJhem9uX3NvY2lhbCI6IkNFTFVMQVJFUyBZIEFDQ0VTT1JJT1MgREVMIFNVUkVTVEUsIFMuQS4gREUgQy5WLiIsIm5vX3RlbGVmb25vXzEiOiI3Nzc3Nzc3Nzc3Iiwibm9fdGVsZWZvbm9fMiI6bnVsbCwiZGlyZWNjaW9uIjoiMjMgTm8gNTNBIEVOVFJFIDggWSAxMCIsImNvbG9uaWEiOiJNRVhJQ08iLCJjaXVkYWQiOiJNw6lyaWRhIiwiZXN0YWRvIjoiWXVjYXTDoW4iLCJjb2RpZ29fcG9zdGFsIjoiOTcxMjUiLCJlc3RhdHVzIjoxLCJvcGVyX2FsdGEiOiJzeXMiLCJmZWNoYV9hbHRhIjoiMjAyMS0xMi0xMlQyMzozMjoyOS45NjBaIiwib3Blcl9tb2RpZmljYWNpb24iOiIwMDAwMDA3MTI4IiwiZmVjaGFfbW9kaWZpY2FjaW9uIjoiMjAyMi0wNi0xM1QxMToyMzoxNy4zODdaIiwib3Blcl9iYWphIjpudWxsLCJmZWNoYV9iYWphIjpudWxsLCJub21icmVfc29jaW8iOm51bGwsImNsYWJlX2ludGVyYmFuY2FyaWEiOm51bGwsImZnX2VzX2Zyb250ZXJpem8iOjB9LCJwcm9maWxlIjp7ImlkIjoxLCJub21icmUiOiJTdXBlciBBZG1pbmlzdHJhZG9yIiwia2V5Ijoic3VwZXJhZG1pbiIsImRlc2NyaXBjaW9uIjpudWxsLCJlc3RhdHVzIjoxLCJtb2R1bGVzIjpbeyJpZCI6MSwiZXN0YXR1cyI6MSwibW9kdWxlIjp7ImlkX21vZHVsbyI6MSwibm9tYnJlX21vZHVsbyI6IkRhc2hib2FyZCIsImRlc2NyaXBjaW9uIjpudWxsLCJlc3RhdHVzIjoxLCJwZXJtaXNzaW9ucyI6W119fSx7ImlkIjoyLCJlc3RhdHVzIjoxLCJtb2R1bGUiOnsiaWRfbW9kdWxvIjoyLCJub21icmVfbW9kdWxvIjoiQ29uZmlndXJhY2lvbiIsImRlc2NyaXBjaW9uIjpudWxsLCJlc3RhdHVzIjoxLCJwZXJtaXNzaW9ucyI6W119fV19fSwiaWF0IjoxNjYyMTM4NDI3LCJleHAiOjE2NjIxNDIwMjd9.9F2DllKKB5Ekw6gYMb7jWE3gFxoxzYbZY8JuysgMtAI',
  code: 200,
};
