export const MACROPAY_LOGO = '/assets/logo.png';

//KEY STORAGES
export const SESSION_KEY_LOCAL_STORAGE = 'session_key_storage';
export const USER_KEY_LOCAL_STORAGE = 'user_key_storage';

export const TOAST_TIMER = 5;
// Generated by https://quicktype.io

export const MIN_TEXT_LENGTH = 2;
export type TO_DEFINE = any;
